spring:
  application:
    name: spring-nextjs-api

  datasource:
    url: jdbc:h2:mem:spring_nextjs

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

  data:
    web:
      pageable:
        default-page-size: 10
